MIMETYPE_EPUB = 'application/epub+zip'
MIMETYPE_HTML = 'application/xhtml+xml'
MIMETYPE_OPF = 'application/oebps-package+xml'
MIMETYPE_NCX = 'application/x-dtbncx+xml'
MIMETYPE_JS = 'text/javascript'
MIMETYPE_CSS = 'text/css'

OPF_PATH = 'OEBPS/content.opf'
NCX_PATH = 'OEBPS/toc.ncx'
CONTAINER_PATH = 'META-INF/container.xml'